import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import { Logo } from '@/components/ui'
import './globals.css'

const quicksand = Quicksand({
    subsets: ['latin'],
    weight: '700',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={`${quicksand.className} h-full antialiased`}>
            <body className="bg-base flex min-h-full flex-col">
                <header className="bg-surface h-15 rounded-t-lg border-2"></header>
                <Logo />
                <main className="p-14">{children}</main>
            </body>
        </html>
    )
}
