import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/store/StoreProvider'
import { Header } from '@/components/ui'

const quicksand = Quicksand({
    subsets: ['latin'],
    weight: '700',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={`${quicksand.className} h-full antialiased`}>
            <body className="bg-base flex min-h-full flex-col">
                <StoreProvider>
                    <Header />
                    <main className="p-14">{children}</main>
                </StoreProvider>
            </body>
        </html>
    )
}
